"use client";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeProvider enableSystem={true} attribute="className">
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
